export type {
  // Manifest types
  PluginLicenseType,
  PluginCategory,
  PluginSource,
  PluginCollectionColumnType,
  PluginCollectionSchema,
  PluginMigrationOperation,
  PluginMigration,
  PluginSettingOption,
  PluginSettingTestAction,
  PluginSettingDefinition,
  PluginPermission,
  PluginCliEndpoint,
  PluginCronDefinition,
  PluginManifest,
  PluginRegistryEntry,
  // Context types
  QueryOptions,
  SidebarItem,
  CliRequest,
  CliResponse,
  CliHandler,
  PluginStorage,
  PluginSecrets,
  PluginDb,
  PluginSettings,
  PluginLogger,
  PluginEvents,
  PluginSessions,
  PluginAi,
  PluginAiStructuredRequest,
  PluginFs,
  PluginHttp,
  PluginCron,
  PluginCli,
  PluginSidebar,
  PluginToast,
  PluginContext,
  PluginAuthUser,
  PluginAuthSession,
  PluginAuth,
  InboxItem,
  PluginInbox,
  RecordingHandle,
  Recording,
  PluginRecording,
  // Text to speech (`tts`)
  SynthesizedSpeech,
  PluginTts,
  // Session history (`sessions.readHistory`)
  HistoryProject,
  HistorySession,
  HistoryMessage,
  HistoryGrantResult,
  PluginSessionHistory,
  // Firebase (`firebase`)
  FirebaseAccount,
  FirebaseProject,
  FirebaseSetupStatus,
  PluginFirebase,
  // Spend reporting (`spend`)
  SpendWindow,
  SpendEngineLine,
  SpendFeatureLine,
  SpendCharge,
  SpendReportBreakdown,
  PluginSpend,
  // Backend types
  PluginBackend,
  PluginActivate,
} from './types/index.js'

// Validators (runtime value exports)
export { manifestSchema, validateManifest, PLUGIN_PERMISSIONS } from './validators/manifest.js'
export type { ManifestValidationResult } from './validators/manifest.js'
